import { UserRecord } from "@/widgets/overview/ui/RecentUsersTable";
type SubscriptionRecord = UserRecord & { card: string } 
export const subscriptionData: SubscriptionRecord[] = [
  {
    id: "1",
    name: "Cameron Williamson",
    email: "alice@example.com",
    plan: "Monthly",
    card: "**** **** **** 1234",
    safeToSpend: 100,
    subscribedAt: "2024-01-15",
    status: "Active",
  },
  {
    id: "2",
    name: "Niloy Tata",
    email: "niloy@example.com",
    plan: "Yearly",
    card: "**** **** **** 5678",
    subscribedAt: "2024-02-18",
    safeToSpend: 250,
    status: "Active",
  },
  {
    id: "3",
    name: "Sophia Chen",
    email: "sophia.chen@example.com",
    plan: "Monthly",
    card: "**** **** **** 9012",
    subscribedAt: "2024-03-22",
    safeToSpend: 340,
    status: "Active",
  },
  {
    id: "4",
    name: "Liam O'Connor",
    email: "liam.oconnor@example.com",
    plan: "Yearly",
    card: "**** **** **** 3456",
    subscribedAt: "2024-04-27",
    safeToSpend: 410,
    status: "Inactive",
  },
  {
    id: "5",
    name: "Isabella Martinez",
    email: "isabella.m@example.com",
    plan: "Monthly",
    card: "**** **** **** 7890",
    subscribedAt: "2024-05-03",
    safeToSpend: 980,
    status: "Active",
  },
  {
    id: "6",
    name: "Wei Zhang",
    email: "wei.zhang@example.com",
    plan: "Monthly",
    card: "**** **** **** 1111",
    subscribedAt: "2024-05-19",
    safeToSpend: 75,
    status: "Pending",
  },
  {
    id: "7",
    name: "Amara Osei",
    email: "amara.osei@example.com",
    plan: "Yearly",
    card: "**** **** **** 2222",
    subscribedAt: "2024-06-01",
    safeToSpend: 530,
    status: "Active",
  },
  {
    id: "8",
    name: "Lucas Müller",
    email: "lucas.muller@example.com",
    plan: "Monthly",
    card: "**** **** **** 3333",
    subscribedAt: "2024-06-08",
    safeToSpend: 90,
    status: "Active",
  },
  {
    id: "9",
    name: "Priya Nair",
    email: "priya.nair@example.com",
    plan: "Monthly",
    card: "**** **** **** 4444",
    subscribedAt: "2024-06-15",
    safeToSpend: 1200,
    status: "Active",
  },
  {
    id: "10",
    name: "Ethan Brooks",
    email: "ethan.brooks@example.com",
    plan: "Monthly",
    card: "**** **** **** 5555",
    subscribedAt: "2024-06-22",
    safeToSpend: 60,
    status: "Inactive",
  },
  {
    id: "11",
    name: "Fatima Al-Hassan",
    email: "fatima.alhassan@example.com",
    plan: "Yearly",
    card: "**** **** **** 6666",
    subscribedAt: "2024-07-04",
    safeToSpend: 310,
    status: "Active",
  },
  {
    id: "12",
    name: "James Kowalski",
    email: "james.k@example.com",
    plan: "Monthly",
    card: "**** **** **** 7777",
    subscribedAt: "2024-07-11",
    safeToSpend: 145,
    status: "Pending",
  },
  {
    id: "13",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@example.com",
    plan: "Monthly",
    card: "**** **** **** 8888",
    subscribedAt: "2024-07-18",
    safeToSpend: 870,
    status: "Active",
  },
  {
    id: "14",
    name: "Chloe Dupont",
    email: "chloe.dupont@example.com",
    plan: "Yearly",
    card: "**** **** **** 9999",
    subscribedAt: "2024-07-25",
    safeToSpend: 480,
    status: "Active",
  },
  {
    id: "15",
    name: "Omar Khalid",
    email: "omar.khalid@example.com",
    plan: "Monthly",
    card: "**** **** **** 0000",
    subscribedAt: "2024-08-02",
    safeToSpend: 200,
    status: "Inactive",
  },
  {
    id: "16",
    name: "Sofia Rossi",
    email: "sofia.rossi@example.com",
    plan: "Yearly",
    card: "**** **** **** 1111",
    subscribedAt: "2024-08-09",
    safeToSpend: 620,
    status: "Active",
  },
  {
    id: "17",
    name: "Daniel Park",
    email: "daniel.park@example.com",
    plan: "Monthly",
    card: "**** **** **** 2222",
    subscribedAt: "2024-08-16",
    safeToSpend: 110,
    status: "Active",
  },
  {
    id: "18",
    name: "Aisha Mensah",
    email: "aisha.mensah@example.com",
    plan: "Monthly",
    card: "**** **** **** 3333",
    subscribedAt: "2024-08-23",
    safeToSpend: 1540,
    status: "Active",
  },
  {
    id: "19",
    name: "Noah Andersen",
    email: "noah.andersen@example.com",
    plan: "Monthly",
    card: "**** **** **** 4444",
    subscribedAt: "2024-09-01",
    safeToSpend: 95,
    status: "Pending",
  },
  {
    id: "20",
    name: "Mei Lin",
    email: "mei.lin@example.com",
    plan: "Yearly",
    card: "**** **** **** 5555",
    subscribedAt: "2024-09-14",
    safeToSpend: 730,
    status: "Active",
  }
];